test: refactor jest test negative test cases - phase 1
hyperledger-cacti/cacti pull request #3488
Opened 2024-08-18 20:45 UTC by ashnashahgrover

## **Commit** to be reviewed
test: refactor jest test negative test cases - phase 1
```
Primary Changes
---------------
1. Refactored all remaining negative test case exception assertions under cacti/packages Removed try-catch blocks, replaced with declarations through jest-extended's own API.
```
Fixes #3483

2024-08-18 20:47 UTC, ashnashahgrover commented
@jagpreetsinghsasan 

Should I make a issue to investigate the inconsistencies in deploy-contract-from-json-xdai.test.ts and make this issue dependent on that?

2024-08-19 21:46 UTC, petermetz reviewed
> @jagpreetsinghsasan 
> Should I make a issue to investigate the inconsistencies in deploy-contract-from-json-xdai.test.ts and make this issue dependent on that? 

@ashnashahgrover Yes please! It's looking good in general but we need to make sure the test assertions are working as intended (and if we found an underlying bug then first we have to fix those in order to be able to prove that the asesrtions themselves work as intended)

2024-08-22 09:58 UTC, outSH requested changes
LGTM, I only found one small things to fix

2024-08-22 09:58 UTC, outSH commented on packages/cactus-verifier-client/src/test/typescript/unit/verifier-factory.test.ts
> +    label: "geth-contract-deploy-and-invoke-using-keychain-v1.test.ts",
Please fix the log label

2024-08-26 20:41 UTC, ashnashahgrover commented on packages/cactus-verifier-client/src/test/typescript/unit/verifier-factory.test.ts
> +    label: "geth-contract-deploy-and-invoke-using-keychain-v1.test.ts",
Fixed this.

2024-09-09 11:58 UTC, outSH approved these changes
LGTM, thank you!

2024-10-15 00:05 UTC, petermetz approved these changes

2024-10-17 23:38 UTC, closed without merging

2024-10-17 23:38 UTC, petermetz commented
Closing this due to inactivity, please feel free to re-open anytime if/when bandwidth is available to take it to the finish line (some of the checks are failing such as the linter)