test(test-plugin-ledger-connector-besu): jestify v21-sign-transaction…
hyperledger-cacti/cacti pull request #3576
Opened 2024-10-08 01:23 UTC by aldousalvarez

### **Commit** to be reviewed
---
test(test-plugin-ledger-connector-besu): jestify v21-sign-transaction-endpoint

Primary Changes
----------------
```
packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/ integration/plugin-validator-besu/v21-sign-transaction-endpoint.test.ts
```
Fixes #3565

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

2024-10-08 07:37 UTC, jagpreetsinghsasan commented
PR-Commit Parity is failing to a known bug: https://github.com/hyperledger-cacti/cacti/issues/3557 (This workflow result can be skipped for evaluating PR for merge)

2024-10-08 08:37 UTC, outSH requested changes
LGTM, I've left only two small nitpicks comments, please have a look, thanks.

2024-10-08 08:37 UTC, outSH commented on packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/v21-sign-transaction-endpoint.test.ts
> +    log.debug(`Cactus Node 1 Host: ${node1Host}`);
Please remove `1` from `httpServer1`, `addressInfo1` and `node1Host`. I see it was named that way in the original test but we can fix it now anyway

2024-10-08 08:37 UTC, outSH commented on packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/v21-sign-transaction-endpoint.test.ts
> +import axios from "axios";
(optional) Please move this import up so that internal imports (from `@hyperledger/*`) occur after external ones

2024-10-09 05:55 UTC, aldousalvarez commented
@outSH re-requested for review, already done with your requested changes. Thank you

2024-10-09 07:21 UTC, outSH approved these changes
Thanks, LGTM!

2024-10-18 03:06 UTC, petermetz approved these changes

2024-10-18 03:53 UTC, petermetz requested changes
My bad, the besu test package's tests are failing, please fix those test failures (I think they were passing before this PR)

[ctp-ledger-connector-besu](https://github.com/hyperledger-cacti/cacti/actions/runs/11397024781/job/31711830616?pr=3576#logs)

2024-10-21 11:30 UTC, aldousalvarez commented
@petermetz re-requested for review, already fixed the requested changes. The besu test packages are now passing. Thank you

2024-10-21 22:29 UTC, petermetz requested changes
@aldousalvarez [ctp-ledger-connector-besu](https://github.com/hyperledger-cacti/cacti/actions/runs/11397024781/job/31711830616?pr=3576#logs) is being skipped, not passing. I've added a fix last week to make it be not skipped (which was a bug in the code change detection logic of ci.yaml) but you seem to have deleted that fix so now it's just being skipped again.

2024-10-22 08:00 UTC, aldousalvarez commented
@petermetz I have fixed the problem where the ctp-ledger-connector-besu is being skipped, and it is now passing. Re-requested for review. Thank you.

2024-10-22 16:25 UTC, petermetz approved these changes
@aldousalvarez LGTM, thank you for the updates!

2024-10-22 16:54 UTC, merged