test(connector-besu): migrate v21-get-past-logs-endpoint to Jest
hyperledger-cacti/cacti pull request #3604
Opened 2024-10-28 10:42 UTC by Udhayakumari

The full file path of the test case:

[packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/
integration/plugin-validator-besu/v21-get-past-logs-endpoint.test.ts](url)

Fixes: #3572

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

2024-10-28 23:37 UTC, petermetz requested changes
@Udhayakumari  +1 to what @outSH said, looking GREAT otherwise! Thank you very much!

2024-10-29 05:25 UTC, Udhayakumari commented
Hello @outSH @petermetz, I have made changes you suggested. Please re-review and let me know!

2024-10-29 06:12 UTC, petermetz approved these changes
@Udhayakumari LGTM, thank you again for the contribution and the updates!

2024-10-29 10:21 UTC, outSH approved these changes

2024-10-31 18:48 UTC, petermetz requested changes
@Udhayakumari Please fix the linter errors. You can run it locally by doing `yarn lint` on the command line.

![image](https://github.com/user-attachments/assets/57818e07-0162-41af-990e-a73a83cd6695)

2024-11-01 06:47 UTC, Udhayakumari commented
@petermetz I have fixed the linter error. Please re-review.

2024-11-01 16:22 UTC, petermetz requested changes

2024-11-01 16:22 UTC, petermetz commented on tools/ci-skip-for-maintainers.js
> +import { readFileSync } from "fs";
@Udhayakumari The linter is now fixed, thank you for that! On another note though, this file shouldn't  be in here, did you maybe accidentally add it during a rebase? Either way, please remove it from the diff and then we are good to go from my side.

2024-11-01 16:24 UTC, petermetz approved these changes

2024-11-01 17:21 UTC, petermetz requested changes
@Udhayakumari Backtracking again: the linter still fails like before so it needs to be fixed first before we can merge. Let me know if you need help:

![image](https://github.com/user-attachments/assets/b1ade748-8864-43ee-b941-1fb096b2713c)

2024-11-04 03:30 UTC, Udhayakumari commented
@petermetz , I have fixed the linter error. Please re-review.

<img width="508" alt="linter-error" src="https://github.com/user-attachments/assets/1e7ee34b-03fd-4ea7-8cdf-9b7ad7c2d73f">

2024-11-04 03:39 UTC, petermetz approved these changes
@Udhayakumari LGTM, thank you!

2024-11-05 00:22 UTC, merged