chore: install secret detection on pre-commit hooks
hyperledger-cacti/cacti pull request #3606
Opened 2024-10-29 07:26 UTC by zondervancalvez

### **Commit** to be reviewed
---
chore: install secret detection on pre-commit hooks
```
Primary Changes
----------------
1. Installed gitleaks for secret detection.
2. This pre-commit checker detects any secrets
or crypto so that it doesn't get pushed to
the github repo.

```
Fixes #2290

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

2024-10-29 08:24 UTC, zondervancalvez commented
![image](https://github.com/user-attachments/assets/cd4f0198-f4aa-4b01-b45b-8d062ed63e5a)

2024-10-31 23:08 UTC, petermetz requested changes
@zondervancalvez A good start, but please add an npm script in the top level package.json that coldstarts the pre-commit hook. The idea is that on-boarding new contributors could run that script ones and have the commit hook enabled after it finished running.

Please also add another npm script that removes the pre-commit hook and cleans up after itself (files downloaded/created during the enabler script )

You could call the scripts `tools:install-pre-commit-secret-detection` and `tools:uninstall-pre-commit-secret-detection`

2024-11-08 15:27 UTC, petermetz commented
@zondervancalvez Are you still working on this?

2024-11-12 05:40 UTC, zondervancalvez commented
> @zondervancalvez Are you still working on this?

@petermetz Yes

2024-11-26 16:21 UTC, petermetz approved these changes

2024-11-28 03:33 UTC, jagpreetsinghsasan commented
@hyperledger-cacti/cacti-maintainers requesting review on this PR

2024-11-28 14:48 UTC, outSH requested changes

2024-11-28 14:48 UTC, outSH commented on package.json
> +    "tools:uninstall-pre-commit-secret-detection": "pre-commit uninstall",
Could you also update our `CONTRIBUTING.md` and / or `BUILD.md` to recommend installing these pre-commits when setting up the environment?

2024-12-05 10:24 UTC, outSH approved these changes
LGTM, thank you!

2024-12-05 15:51 UTC, merged