ci(github): fix type exports in packages/cactus-common
hyperledger-cacti/cacti pull request #3649
Opened 2024-11-21 16:53 UTC by ruzell22

### Commit to be reviewed
---
ci(github): fix type exports in packages/cactus-common
```
Primary Changes
---------------
1. Remove packages/cactus-common/hyperledger-cactus-common-*.tgz in ignore
paths in get-all-tgz-path.ts file
2. Added the missing LogLevelDesc in index.js and index.d.ts as per attw
-f json error log
```

Fixes: #3635

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

2024-11-21 16:56 UTC, ruzell22 commented
Before fix:
![image](https://github.com/user-attachments/assets/6e5d31dc-8b7a-4583-b1bc-cddd51eecbd7)
adding `-f json` to attw command, it shows which file and which problem with export it is having.

After fix:
![image](https://github.com/user-attachments/assets/8d425fa2-2988-4ebf-a434-6af6672f2672)
`yarn run custom-checks` and attw with and without `-f json` flag are all passing

2024-11-21 17:20 UTC, petermetz requested changes
@ruzell22 Thank you! For your changes to be version controlled you cannot change index.js, you must change index.ts (which is the one that gets compiled to index.js)

2024-11-25 16:03 UTC, outSH approved these changes
LGTM, I've re-run failed yarn codegen check to see if it's caused by the PR or not

2024-11-26 17:23 UTC, petermetz requested changes

2024-11-26 17:23 UTC, petermetz commented on packages/cactus-common/src/main/typescript/index.ts
> +export type LogLevelDesc = (typeof LogLevel)[keyof typeof LogLevel];
@ruzell22 
1. Please do not write code directly in index.ts, it is meant to collect the public API surface exports and that will very noisy if you start writing code directly in it.
2. Could you make the LogLevelDesc type a match to what is defined in `packages/cactus-common/node_modules/loglevel/index.d.ts` ? There's nothing wrong by the looks of it with what you have here, but it is the safest if we use the exact same definition that the library uses internally to reduce the risk of type compatibility issues later on.

```typescript
   /**
     * Log levels
     */
    interface LogLevel {
        TRACE: 0;
        DEBUG: 1;
        INFO: 2;
        WARN: 3;
        ERROR: 4;
        SILENT: 5;
    }

    /**
     * Possible log level numbers.
     */
    type LogLevelNumbers = LogLevel[keyof LogLevel];

    /**
     * Possible log level descriptors, may be string, lower or upper case, or number.
     */
    type LogLevelDesc = LogLevelNumbers
        | 'trace'
        | 'debug'
        | 'info'
        | 'warn'
        | 'error'
        | 'silent'
        | keyof LogLevel;
```

2024-12-01 05:11 UTC, petermetz approved these changes
@ruzell22 LGTM, thank you for the updates!

2024-12-01 05:14 UTC, petermetz commented on packages/cactus-common/src/main/typescript/index.ts
> +export type LogLevelDesc = (typeof LogLevel)[keyof typeof LogLevel];
@ruzell22 It checks out, thank you.

2024-12-01 20:40 UTC, merged