test(ghcr-example-supply-chain-app): fix missing patch @ionic-native
hyperledger-cacti/cacti pull request #3651
Opened 2024-11-25 05:13 UTC by zondervancalvez

## Commit to be reviewed

test(ghcr-example-supply-chain-app): fix missing patch @ionic-native
```
Primary Changes
----------------
1. Updated the NVM version to 20.11.1 and added
the necessary yarn patch path to build the image
```
Fixes #3601

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

2024-11-25 09:59 UTC, jagpreetsinghsasan commented
@zondervancalvez codegen is failing

2024-11-26 17:19 UTC, petermetz requested changes
@zondervancalvez Looking good in general but I have a few nits:
1. If you need the NodeJS upgrade then please explain why. Otherwise remove it.
2. The `.yarn/` directory is 700 MB. The patch that is in it is only a few KB. Could you please try to only include the patch file with an otherwise empty .yarn/ directory so we don't have to increase the image size by this much just for the little patch.

2024-12-05 23:24 UTC, petermetz approved these changes

2024-12-05 23:24 UTC, petermetz commented
@hyperledger-cacti/cacti-maintainers bump

2024-12-06 11:06 UTC, outSH approved these changes

2024-12-09 18:59 UTC, merged