ci(github): update publishing workflows to use github.repository_owner
hyperledger-cacti/cacti pull request #3683
Opened 2024-12-10 04:31 UTC by adrianbatuto

Primary Changes
----------------
1. Updated publishing workflows to use gitHub.repository_owner variable

Fixes #3597

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

2024-12-10 04:35 UTC, adrianbatuto commented
Adding here the screenshots of the published packages after running the workflows.
![image](https://github.com/user-attachments/assets/55e74a94-059d-400c-96ae-9bca0dfa609d)
![image](https://github.com/user-attachments/assets/7e6d0e4d-d7ce-4d33-9ae3-5dc3da382ce7)

2024-12-11 05:40 UTC, jagpreetsinghsasan approved these changes
Looks good to me.
@petermetz does the username `hyperledger-ghci` remains the same? (We are changing the `hyperledger` prefix so I think we will need a ticket for that as well once Cacti moves to the new org structure)

2024-12-12 04:32 UTC, petermetz requested changes
> Looks good to me. @petermetz does the username `hyperledger-ghci` remains the same? (We are changing the `hyperledger` prefix so I think we will need a ticket for that as well once Cacti moves to the new org structure)

@jagpreetsinghsasan I'm not sure either. Based on the screenshot my guess is that the git username and user email are not actually being used for the authentication with npm at all. So it might be that we can just simply remove them instead modifying them to use the variables. I'm deducing this from the fact that it worked on @adrianbatuto 's fork despite the username being different.

@adrianbatuto I think you can just remove those lines and re-test on your fork and if it can still publish to npm then we are golden.

2024-12-18 05:44 UTC, adrianbatuto commented
> > Looks good to me. @petermetz does the username `hyperledger-ghci` remains the same? (We are changing the `hyperledger` prefix so I think we will need a ticket for that as well once Cacti moves to the new org structure)
> 
> @jagpreetsinghsasan I'm not sure either. Based on the screenshot my guess is that the git username and user email are not actually being used for the authentication with npm at all. So it might be that we can just simply remove them instead modifying them to use the variables. I'm deducing this from the fact that it worked on @adrianbatuto 's fork despite the username being different.
> 
> @adrianbatuto I think you can just remove those lines and re-test on your fork and if it can still publish to npm then we are golden.

Sorry for the late response, I just got back from leave. 
I will look into this and let you know.

2024-12-19 06:03 UTC, adrianbatuto commented
@petermetz I was able to publish successfully after removing the user email and name. 

![image](https://github.com/user-attachments/assets/6427203c-fa21-49f1-bc37-478757a83f44)

2024-12-19 11:07 UTC, outSH approved these changes

2025-01-30 17:47 UTC, petermetz approved these changes
@adrianbatuto No worries, sorry for the slow response here as well. That sounds promising, I think we are good to go from my side as well in that case. Thank you very verifying once again!

2025-01-30 18:38 UTC, merged