ci(github): add dependency version consistency check
hyperledger-cacti/cacti pull request #3699
Opened 2024-12-11 05:25 UTC by jagpreetsinghsasan

## Commit to be reviewed

ci(github): add dependency version consistency check 

    Primary Changes
    ---------------
    1. Added a new custom check which checks if there are any inconsistency with the dependency version, which is already being used with an exsisting package.

    Changes needed to incorporate 1)
    -------------------------------
    2. Added a new dependency in the root package.json
    3. Added a new npm script in the root package.json
    4. Updated the lock file for the dependency inclusion

Fixes #3612

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

2024-12-11 05:30 UTC, jagpreetsinghsasan commented
@petermetz I have created multiple tickets to address the fix for this (#3684 till #3698)

2024-12-12 04:21 UTC, petermetz requested changes
@jagpreetsinghsasan Almost perfect, just please add the currently bad dependencies to the ignore list so that when we merge this PR the custom checks are passing.
Then we can remove the ignore declarations as we fix the problems chunk by chunk and finally (hopefully) end up with no ignores at all.

2024-12-17 04:52 UTC, jagpreetsinghsasan commented
> @jagpreetsinghsasan Almost perfect, just please add the currently bad dependencies to the ignore list so that when we merge this PR the custom checks are passing. Then we can remove the ignore declarations as we fix the problems chunk by chunk and finally (hopefully) end up with no ignores at all.

@petermetz shall I add the ignore list with packages in it (instead of dependencies)? This is because the way we are targetting a fix for this to fix it `per-package` basis. A single dependency mismatch can happen in multiple packages and so tracking the ignore list (if it is `per-dependency` basis) will be much harder against the resolved issue (the 14 phases of addressing the fix for this)

2025-01-30 17:53 UTC, petermetz approved these changes
@jagpreetsinghsasan Yes, that works as well, in this regard, I'm OK with whatever is more convenient because eventually we'll empty out the list either way. Thank you!

2025-02-14 13:17 UTC, outSH approved these changes

2025-02-16 01:02 UTC, merged