ci(github): fix type exports in packages/cacti-plugin-copm-fabric
hyperledger-cacti/cacti pull request #3702
Opened 2024-12-12 16:43 UTC by ruzell22

### Commit to be reviewed
---
ci(github): fix type exports in packages/cacti-plugin-copm-fabric
```
Primary Changes
---------------
1. Removed packages/cacti-plugin-copm-fabric/hyperledger-cacti-cacti-plugin-
copm-fabric-*.tgz in ignore paths in get-all-tgz-path.ts file
2. Added main, module, types, and files in package.json
```

Fixes: #3629

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

2024-12-12 16:44 UTC, ruzell22 commented
With the code changes, attw gives all green passing result
![image](https://github.com/user-attachments/assets/0d504532-c643-4a54-82ec-4cc39139bf95)
![image](https://github.com/user-attachments/assets/9b443450-14fe-4ace-886d-c2d2b9cb8f35)

2024-12-12 21:33 UTC, petermetz requested changes
@ruzell22 LGTM with comments: Please fix the merge conflict - otherwise it's looking good to me.

2024-12-18 06:08 UTC, ruzell22 commented
Apologies for the delay on pushing, I had issue with my device and the yarn run configure with fork in the past few days but I have updated my fork now to resolve merge conflict, thanks @petermetz

2024-12-19 11:08 UTC, outSH approved these changes

2025-01-06 07:07 UTC, jagpreetsinghsasan approved these changes

2025-02-06 04:19 UTC, petermetz approved these changes

2025-02-06 04:19 UTC, petermetz commented
@ruzell22 Please fix the merge conflict, otherwise it's good to go!

2025-02-07 04:55 UTC, ruzell22 commented
@petermetz upon testing custom-checks again with the latest repo to resolve merge conflict, it failed on two different packages so I added them on the ignore path list so that it will pass and created 2 new tickets for it as well, #3740 #3741 
![image](https://github.com/user-attachments/assets/a19d8a86-97b3-4b55-a6b5-1d3997c3f0b9)

2025-02-08 01:23 UTC, petermetz commented
> @petermetz upon testing custom-checks again with the latest repo to resolve merge conflict, it failed on two different packages so I added them on the ignore path list so that it will pass and created 2 new tickets for it as well, #3740 #3741 ![image](https://private-user-images.githubusercontent.com/89818529/410753519-a19d8a86-97b3-4b55-a6b5-1d3997c3f0b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg5NzgwNTYsIm5iZiI6MTczODk3Nzc1NiwicGF0aCI6Ii84OTgxODUyOS80MTA3NTM1MTktYTE5ZDhhODYtOTdiMy00YjU1LWE2YjUtMWQzOTk3YzNmMGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjA4VDAxMjIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYjM1MjM4MzI4ZjU1Mjg0MzhmYTJiY2M1YTVhMDBmYmE2NTYxMTA2ZjA5Mjg2MmY1MjNhN2RlMGQxMzAxNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bX106auoH_2qDUiF6UkYFMFNMgmeVu50Ek2UXxqcxjM)

@ruzell22 Got it, thank you!

2025-02-08 04:04 UTC, merged