fix(dast): ccp, sshconfig missing
hyperledger-cacti/cacti pull request #3705
Opened 2024-12-18 05:58 UTC by raynatopedrajeta

Primary Changes
----------------
1. Fix the issue on plugin-ledger-connector-fabric that throws an error when there is no sshConfig available.

Fixes #3671

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

2024-12-18 06:05 UTC, jagpreetsinghsasan commented on .github/workflows/.dast-nuclei-cmd-api-server.yaml
> +        run: jq '.plugins += [{ "packageName":"@hyperledger/cactus-plugin-ledger-connector-fabric", "type":"org.hyperledger.cactus.plugin_import_type.LOCAL", "action":"org.hyperledger.cactus.plugin_i
Again, there should be `NO` changes to this piece of code (That is the objective of the task)

2025-01-13 04:09 UTC, jagpreetsinghsasan requested changes

2025-01-13 04:09 UTC, jagpreetsinghsasan commented on .github/workflows/.dast-nuclei-cmd-api-server.yaml
> +      - run: jq '.expressJwtOptions.secret = "-----BEGIN PUBLIC KEY-----\n$(cat public_key.pem)\n-----END PUBLIC KEY-----" |
The public key is generated with those tags by default, please double check

2025-01-13 04:09 UTC, jagpreetsinghsasan commented on packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
> +      // throw new Error("Cannot instantiate Fabric connector without SSH config");
Before this comment please add this
```
TODO: Temporarily commenting this code so that we do not have breaking changes, will be fixed by ISSUE_NUM
```

2025-01-13 04:09 UTC, jagpreetsinghsasan commented on packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
> +      console.log("The check for sshConfig has been temporarily removed");
Please remove this

2025-01-13 04:09 UTC, jagpreetsinghsasan commented on .github/workflows/.dast-nuclei-cmd-api-server.yaml
> +
Please remove these new lines

2025-01-16 06:41 UTC, raynatopedrajeta commented on .github/workflows/.dast-nuclei-cmd-api-server.yaml
> +
Hello @jagpreetsinghsasan ,

I've compared this per line and no changes on my end. Not sure why these empty lines are tagged as changes.

Any suggestions for this?

Thank you!

Rayn

2025-01-28 09:55 UTC, jagpreetsinghsasan submitted a review, later dismissed

2025-01-28 09:55 UTC, jagpreetsinghsasan commented on .github/workflows/.dast-nuclei-cmd-api-server.yaml
> +
When you add the changed files (before commit), you can revert these changes there itself, the change here is, earlier it was `newline` and now it is `newline,space`

2025-01-28 09:55 UTC, jagpreetsinghsasan commented on packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
> +      // throw new Error("Cannot instantiate Fabric connector without SSH config");
I think you straightaway copy pasted my line even though we discussed in the meeting to create a new task to fix this and then replace it with `ISSUE_NUM`.

2025-02-06 04:21 UTC, petermetz requested changes

2025-02-06 04:21 UTC, petermetz commented on packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
> +      // throw new Error("Cannot instantiate Fabric connector without SSH config");
+1 raynatopedrajeta The comment is almost spot on, just please make sure to open an issue and put the number of that issue there in place of `ISSUE_NUM`

2025-02-18 03:46 UTC, jagpreetsinghsasan commented
All good from my end.

2025-04-03 01:22 UTC, petermetz approved these changes

2025-04-03 07:08 UTC, outSH approved these changes

2025-04-04 20:11 UTC, merged